default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: python -m ruff check --fix
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
      - id: ruff-format
        name: ruff format
        entry: python -m ruff format
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
